# Generated by Django 2.0.2 on 2018-05-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Requerido. 50 carácteres como máximo.', max_length=50)),
                ('course', models.CharField(help_text='Requerido. 50 carácteres como máximo.', max_length=50)),
                ('exercises', models.ManyToManyField(blank=True, to='exercises.Exercise')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.School')),
            ],
            options={
                'verbose_name_plural': 'Asignaturas',
                'verbose_name': 'Asignatura',
            },
        ),
    ]
