# Generated by Django 2.0.2 on 2018-03-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0002_auto_20180314_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Requerido. 50 carácteres como máximo.', max_length=50, unique=True)),
                ('course', models.CharField(help_text='Requerido. 50 carácteres como máximo.', max_length=50)),
                ('code', models.CharField(help_text='Requerido.', max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.School')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
