# Generated by Django 2.0.2 on 2018-03-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Requerido. 50 carácteres como máximo.', max_length=50),
        ),
    ]
