# Generated by Django 2.0.2 on 2018-03-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20180331_1314'),
        ('subjects', '0002_auto_20180331_1825'),
    ]

    operations = [
    ]
