# Generated by Django 2.0.2 on 2018-03-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20180318_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
