# Generated by Django 2.0.2 on 2018-03-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
    ]
