# Generated by Django 2.0.2 on 2018-03-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultSubjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsubject',
            name='name',
            field=models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50),
        ),
    ]
