# Generated by Django 2.0.2 on 2018-03-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaultSubjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultsubject',
            options={'verbose_name_plural': 'Default Subjects'},
        ),
    ]
