# Generated by Django 2.0.2 on 2018-03-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultSubjects', '0002_auto_20180318_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultsubject',
            name='code',
        ),
        migrations.AlterField(
            model_name='defaultsubject',
            name='course',
            field=models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50),
        ),
    ]
