# Generated by Django 2.0.2 on 2018-03-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaultSubjects', '0003_auto_20180318_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultsubject',
            options={'verbose_name': 'Asignatura Básica', 'verbose_name_plural': 'Asignaturas Básicas'},
        ),
    ]
