# Generated by Django 2.0.2 on 2018-03-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaultSubjects', '0004_auto_20180320_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultsubject',
            options={'verbose_name': 'Asignatura Genérica', 'verbose_name_plural': 'Asignaturas Genéricas'},
        ),
    ]
