# Generated by Django 2.0.2 on 2018-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyExerciseValue', models.DecimalField(decimal_places=2, default=4.0, max_digits=9, verbose_name='Precio de compra')),
                ('profitExerciseValue', models.DecimalField(decimal_places=2, default=1.0, max_digits=9, verbose_name='Ganancias Climbcode')),
                ('promoteExerciseValue', models.DecimalField(decimal_places=2, default=1.0, max_digits=9, verbose_name='Precio de promoción')),
            ],
            options={
                'verbose_name_plural': 'Precios',
                'verbose_name': 'Precios',
            },
        ),
    ]
