# Generated by Django 2.0.2 on 2018-03-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elementPrices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementprice',
            options={'verbose_name_plural': 'Element Prices'},
        ),
    ]
