# Generated by Django 2.0.2 on 2018-03-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementPrices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementprice',
            name='profitExerciseValue',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=9),
        ),
    ]
