# Generated by Django 2.0.2 on 2018-03-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elementPrices', '0002_auto_20180318_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementprice',
            options={'verbose_name': 'Precios', 'verbose_name_plural': 'Precios'},
        ),
    ]
