# Generated by Django 2.0.2 on 2018-03-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Código', 'verbose_name_plural': 'Códigos'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Parámetro', 'verbose_name_plural': 'Parámetros'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Gráfica', 'verbose_name_plural': 'Gráficas'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Texto', 'verbose_name_plural': 'Textos'},
        ),
    ]
