# Generated by Django 2.0.2 on 2018-03-17 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BASIC', help_text='Requerido. 50 carácteres como máximo.', max_length=50, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto. Debe ser BASIC, MEDIUM, LARGE', regex='^BASIC$')])),
                ('numUsers', models.PositiveIntegerField(default=0)),
                ('numFreeExercises', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'LicenseTypes',
            },
        ),
    ]
