# Generated by Django 2.0.2 on 2018-03-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50)),
                ('description', models.TextField()),
                ('sales', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('promoted', models.BooleanField()),
                ('startPromotionDate', models.DateField(blank=True, null=True)),
                ('endPromotionDate', models.DateField(blank=True, null=True)),
                ('draft', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Exercises',
            },
        ),
    ]
