# Generated by Django 2.0.2 on 2018-05-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defaultSubjects', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50)),
                ('description', models.TextField()),
                ('sales', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(choices=[('Fácil', 'Fácil'), ('Medio', 'Medio'), ('Difícil', 'Difícil')], default='Fácil', max_length=10)),
                ('promoted', models.BooleanField()),
                ('startPromotionDate', models.DateField(blank=True, null=True)),
                ('endPromotionDate', models.DateField(blank=True, null=True)),
                ('draft', models.BooleanField(default=True)),
                ('example', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='defaultSubjects.DefaultSubject')),
                ('programmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Programmer')),
            ],
            options={
                'verbose_name_plural': 'Ejercicios',
                'verbose_name': 'Ejercicio',
            },
        ),
    ]
