# Generated by Django 2.0.2 on 2018-04-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de compra')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de compra')),
                ('paymentMethod', models.CharField(choices=[('Paypal', 'Paypal'), ('Free', 'Free')], default='Paypal', max_length=20, verbose_name='Tipo de Pago')),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.Exercise')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.School')),
            ],
            options={
                'verbose_name': 'Ticket de Compra',
                'verbose_name_plural': 'Tickets de Compra',
            },
        ),
    ]
