# Generated by Django 2.0.2 on 2018-03-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmer',
            options={'verbose_name_plural': 'Programmers'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teachers'},
        ),
        migrations.AddField(
            model_name='student',
            name='school_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.School'),
        ),
    ]
