# Generated by Django 2.0.2 on 2018-03-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0001_initial'),
        ('actors', '0001_initial'),
        ('subjects', '0001_initial'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.School'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='school',
            name='exercises',
            field=models.ManyToManyField(to='exercises.Exercise'),
        ),
        migrations.AddField(
            model_name='school',
            name='provinces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provinces.Province'),
        ),
    ]
