# Generated by Django 2.0.2 on 2018-03-14 19:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20180314_2010'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.School'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='phone',
            field=models.CharField(help_text='Requerido. 9 dígitos como máximo.', max_length=11, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^(\\d{3})(\\-)(\\d{3})(\\-)(\\d{3})$')]),
        ),
    ]
