# Generated by Django 2.0.2 on 2018-03-18 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20180318_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='dni',
            field=models.CharField(help_text='Requerido. 8 dígitos y una letra.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^([0-9]{8})([TRWAGMYFPDXBNJZSQVHLCKE])$')]),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='dni',
            field=models.CharField(help_text='Requerido. 8 dígitos y una letra.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^([0-9]{8})([TRWAGMYFPDXBNJZSQVHLCKE])$')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='identificationCode',
            field=models.CharField(help_text='Requerido. 9 dígitos como máximo.', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='postalCode',
            field=models.CharField(help_text='Requerido. 5 dígitos como máximo.', max_length=5, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^(\\d{5})$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='dni',
            field=models.CharField(help_text='Requerido. 8 dígitos y una letra.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^([0-9]{8})([TRWAGMYFPDXBNJZSQVHLCKE])$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dni',
            field=models.CharField(help_text='Requerido. 8 dígitos y una letra.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^([0-9]{8})([TRWAGMYFPDXBNJZSQVHLCKE])$')]),
        ),
    ]
