# Generated by Django 2.0.2 on 2018-03-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20180318_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='identificationCode',
            field=models.CharField(help_text='Requerido. CIF para escuelas; Código de Centro para academías.', max_length=9, null=True),
        ),
    ]
