# Generated by Django 2.0.2 on 2018-03-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_auto_20180318_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='provinces',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='school',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='exercises.Exercise'),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('High School', 'High School'), ('Academy', 'Academy')], default='High School', max_length=11),
        ),
    ]
