# Generated by Django 2.0.2 on 2018-03-18 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_auto_20180318_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='postalCode',
            field=models.CharField(help_text='Requerido. 5 dígitos como máximo.', max_length=5, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^(\\d{5})$')], verbose_name='Postal Code'),
        ),
    ]
