# Generated by Django 2.0.2 on 2018-03-18 15:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0009_auto_20180318_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='userAccount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='dni',
            field=models.CharField(help_text='Requerido. 8 dígitos y una letra.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^([0-9]{8})([TRWAGMYFPDXBNJZSQVHLCKE])$')], verbose_name='D.N.I.'),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='dni',
            field=models.CharField(help_text='Requerido. 8 dígitos y una letra.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^([0-9]{8})([TRWAGMYFPDXBNJZSQVHLCKE])$')], verbose_name='D.N.I.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='identificationCode',
            field=models.CharField(help_text='Requerido. CIF para escuelas; Código de Centro para academías.', max_length=9, null=True, verbose_name='CIF or Center Code'),
        ),
        migrations.AlterField(
            model_name='school',
            name='teachingType',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20, verbose_name='Teaching Type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dni',
            field=models.CharField(help_text='Requerido. 8 dígitos y una letra.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^([0-9]{8})([TRWAGMYFPDXBNJZSQVHLCKE])$')], verbose_name='D.N.I.'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dni',
            field=models.CharField(help_text='Requerido. 8 dígitos y una letra.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^([0-9]{8})([TRWAGMYFPDXBNJZSQVHLCKE])$')], verbose_name='D.N.I.'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.School', verbose_name='School'),
        ),
    ]
