# Generated by Django 2.0.2 on 2018-03-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0012_auto_20180318_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.School', verbose_name='School'),
        ),
    ]
