# Generated by Django 2.0.2 on 2018-03-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0013_auto_20180318_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actores'},
        ),
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradres'},
        ),
        migrations.AlterModelOptions(
            name='programmer',
            options={'verbose_name': 'Programador', 'verbose_name_plural': 'Programadores'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Escuela', 'verbose_name_plural': 'Escuelas'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
