# Generated by Django 2.0.2 on 2018-03-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0014_auto_20180320_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
    ]
