# Generated by Django 2.0.2 on 2018-03-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0015_auto_20180320_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='centerName',
            field=models.CharField(help_text='Requerido. 50 carácteres como máximo.', max_length=50, null=True),
        ),
    ]
