# Generated by Django 2.0.2 on 2018-03-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boxes.Code')),
            ],
            options={
                'verbose_name_plural': 'Parameters',
            },
        ),
    ]
