# Generated by Django 2.0.2 on 2018-03-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenseTypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numUsers', models.PositiveIntegerField(default=0)),
                ('numFreeExercises', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('licenseType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='licenseTypes.LicenseType')),
            ],
            options={
                'verbose_name_plural': 'Licenses',
            },
        ),
    ]
