# Generated by Django 2.0.2 on 2018-05-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numUsers', models.PositiveIntegerField(default=0, verbose_name='Número de usuarios')),
                ('numFreeExercises', models.PositiveIntegerField(default=0, verbose_name='Ejercicios Gratuitos')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio')),
                ('startDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Inicio')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='Fecha de Vigencia')),
            ],
            options={
                'verbose_name_plural': 'Licencias',
                'verbose_name': 'Licencia',
            },
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BÁSICA', help_text='Requerido. 50 carácteres como máximo.', max_length=50)),
                ('numUsers', models.PositiveIntegerField(default=0)),
                ('numFreeExercises', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Licencias Tipo',
                'verbose_name': 'Licencia Tipo',
            },
        ),
        migrations.AddField(
            model_name='license',
            name='licenseType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenses.LicenseType'),
        ),
        migrations.AddField(
            model_name='license',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.School'),
        ),
    ]
