# Generated by Django 2.0.2 on 2018-03-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vigencia'),
        ),
        migrations.AlterField(
            model_name='license',
            name='numFreeExercises',
            field=models.PositiveIntegerField(default=0, verbose_name='Ejercicios Gratuitos'),
        ),
        migrations.AlterField(
            model_name='license',
            name='numUsers',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de usuarios'),
        ),
        migrations.AlterField(
            model_name='license',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='license',
            name='startDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
