# Generated by Django 2.0.2 on 2018-03-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Licencia', 'verbose_name_plural': 'Licencias'},
        ),
        migrations.AlterModelOptions(
            name='licensetype',
            options={'verbose_name': 'Licencia Tipo', 'verbose_name_plural': 'Licencias Tipo'},
        ),
    ]
